package br.com.logisticsystem.models;

public enum TipoOperacao {
    CADASTRAR_ATENDIMENTO,
    ATENDER_ATENDIMENTO,
    ALTERAR_PRIORIDADE_ATENDIMENTO,
    REMOVER_ATENDIMENTO,

    CADASTRAR_PEDIDO,
    ATUALIZAR_PEDIDO,
    ALTERAR_STATUS_PEDIDO,
    ALTERAR_PRIORIDADE_PEDIDO,
    REMOVER_PEDIDO,

    CADASTRAR_ENTREGA,
    ALTERAR_PRIORIDADE_ENTREGA,
    ALTERAR_STATUS_ENTREGA,
    ALTERAR_ROTA_ENTREGA,
    CONCLUIR_ENTREGA,
    CANCELAR_ENTREGA,
}
