package br.com.logisticsystem.models;

public enum TipoOperacao {
    CADASTRAR_PEDIDO,
    REMOVER_PEDIDO,
    ALTERAR_PRIORIDADE_PEDIDO,
    CADASTRAR_ENTREGA,
    CANCELAR_ENTREGA,
    ALTERAR_STATUS_ENTREGA,
    ALTERAR_ROTA_ENTREGA,
    ALTERAR_PRIORIDADE_ATENDIMENTO
}
